dist: trusty
sudo: required

language: generic

install:
  - sudo apt-get update
  - sudo apt-get install -y git python-pip curl
  - sudo pip install awscli
  - sudo pip install cloudformation

script:
  - ./vars.sh
  - aws cloudformation create-stack --stack-name Docksal-CI-Builder --template-body file://template.json --parameters file://parameters.json
